# This is a makefile for running performance tests

# FIXME: download
GRINDER_HOME=~/Desktop/grinder-3.2
JYTHON_HOME=/usr/share/jython

# Must be absolute
TMP_DIR=$(CURDIR)/tmp
PYTHON_CACHEDIR=${TMP_DIR}/python/cachedir
LOG_DIR=$(TMP_DIR)/logs

JAVA_CMD=java
CLASSPATH=${GRINDER_HOME}/lib/grinder.jar

JVM_ARGS=-Dgrinder.logDirectory=$(LOG_DIR)

GRINDER_JVM_ARGS="-Dpython.cachedir=${PYTHON_CACHEDIR} \
	-Dpython.home=${JYTHON_HOME}"

JAVA_ARGS=-Dgrinder.jvm.arguments=$(GRINDER_JVM_ARGS) $(JVM_ARGS)

GRINDER_CMD=${JAVA_CMD} -classpath ${CLASSPATH} $(JAVA_ARGS)


# *** Top level targets ***

start-grinder-console:
	${GRINDER_CMD} net.grinder.Console &

stop-grinder-console:
	# TODO:

stop-grinder-receiver:
	# TODO: Variable to tidy  up, and catch error for non-existant process
	pkill -fx  -P \
		`pgrep -fx "java.*net.grinder.Grinder.*receiver.properties"` \
		".*net.grinder.engine.process.WorkerProcessEntryPoint"

	pkill -fx "java.*net.grinder.Grinder.*receiver.properties"

init-rabbit-streams:
	make stop-core-nox 
	make cleandb
	make start-core-nox
	make create-fresh-accounts
	make start-orchestrator-nox


run-short-thrash-test:
	${MAKE} -f Makefile.test TEST=http2plain STREAM=empty run-perf-test

run-perf-test: create-cachedir init-orchestrator
	${GRINDER_CMD} -Dgrinder.hostID=sender1 net.grinder.Grinder \
		test/performance/tests/${TEST}/sender.properties &

# *** End top level targets ***

create-cachedir:
	mkdir -p ${PYTHON_CACHEDIR}
	chmod a+rw ${PYTHON_CACHEDIR}

start-grinder-receiver: create-cachedir
	${GRINDER_CMD} -Dgrinder.hostID=receiver net.grinder.Grinder \
		test/performance/tests/${TEST}/receiver.properties &

init-orchestrator: start-grinder-receiver
	sbin/import_config.py test/performance/streams/${STREAM}
	make start-orchestrator-nox 
