#!/bin/sh
EBIN_DIR=./ebin
RFC4627_BIN=../build/opt/erlang-rfc4627/ebin
ERLAMQP_BIN=../build/opt/rabbitmq-erlang-client/ebin
RABBIT_BIN=../build/opt/rabbitmq/ebin
IBROWSE_BIN=../build/opt/ibrowse/ebin
MOCHIWEB_BIN=../build/opt/mochiweb


ERL_PATH_OPTS="-pa $EBIN_DIR -pa $RFC4627_BIN -pa $ERLAMQP_BIN -pa $RABBIT_BIN -pa $IBROWSE_BIN -pa $MOCHIWEB_BIN"
erl $ERL_PATH_OPTS -boot start_sasl -sname orchestrator -s orchestrator -orchestrator couch_base_url '"http://127.0.0.1:5984/"' -orchestrator root_config_url '"http://127.0.0.1:5984/feedshub_status/root_config"'
