#!/bin/sh
set -eu

# see ./streams-server re using readlink here.
CMD="$0"
while [ -L "$CMD" ]; do CMD=readlink "$CMD"; done

exec erl \
    -pa "$(dirname ${CMD})/../ebin" \
    -noinput -hidden \
    -sname streamsctl \
    -s streams_control \
    -extra "$@"
